language: c

arch:
  - amd64
  - arm64-graviton2

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make 
#  - ./turbobench -eCI -v0 turbobench  
#  - find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -exec cat {} \; > csrc
#  - ./turbobench -eCI -v0 csrc  

matrix:
  include:
    - name: amd64-linux-gcc
      arch: amd64
      compiler: gcc
      script:
        - make
        - ./turbobench -eCI2 -v0 turbobench  
        - find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -exec cat {} \; > csrc
    - name: amd64-linux-gcc
      arch: arm64-graviton2
      virt: lxd
      group: edge
      compiler: gcc
      script:
        - make
        - ./turbobench -eCI2 -v0 turbobench  
        - find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -exec cat {} \; > csrc
#        - ./turbobench -eCI2 -v0 csrc  

    - name: amd64-linux-clang
      arch: amd64 
      compiler: clang
      script:
        - make
#        - ./turbobench -eCI2 -v0 turbobench  
#        - find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -exec cat {} \; > csrc
#        - ./turbobench -eCI2 -v0 csrc
    - name: amd64-linux-clang
      arch: arm64-graviton2
      virt: lxd
      group: edge
      compiler: clang
      script:
        - make
#        - ./turbobench -eCI2 -v0 turbobench  
#        - find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -exec cat {} \; > csrc
#        - ./turbobench -eCI2 -v0 csrc
  exclude:
      arch: s390x 
      compiler: clang

